name: flutter_e2e_test_sample
description: "Flutter E2E test sample"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  gap: ^3.0.1
  go_router: ^13.0.0
  graphql_flutter: ^5.2.0-beta.6

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.13.11
  integration_test:
    sdk: flutter
  patrol: ^3.3.0
  pedantic_mono: ^1.25.0

flutter:
  uses-material-design: true
